---
title: "Determine best model fits"
author: "Alex Cope"
date: '2023-05-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ape)
library(cowplot)
library(ggpointdensity)
library(ggtree)
library(scales)
suppressMessages(source("helperFunctions.R"))

cleanSpeciesLabels <- function(x)
{
   y <- x %>% str_remove(".max.cds") %>% 
          str_extract("[a-z]+_[a-z]+") %>%
          str_split("_") %>% 
          lapply(function(x){paste0(toupper(substring(x[1],1,1)),". ",x[2])})
          #lapply(function(x){paste(str_to_sentence(x[1]),x[2])})
  unlist(y)
}


cleanTree <- function(tree,target.species)
{
  tips.to.drop <- tree$tip.label[which(!(tree$tip.label %in% target.species))]
  cleaned <- drop.tip(tree,tips.to.drop)
  return(cleaned)
}


cleanColumnNames <- function(col_name,list_of_option)
{
  ## find potential column name from list of options
  index <- unlist(purrr::map(col_name, 
            function(x){
              ## this species will match "metschnikowia_matae_maris.max.cds" and "metschnikowia_matae.max.cds", so force it to match the latter
              if (x == "metschnikowia_matae")
                {
                  x <- paste0(x,".max.cds")
                }
              str_which(list_of_option,x)
            }
    ))
  return(list_of_option[index])
}

createEmpvsROCdf <- function(target.species,k1.phi,k2.phi,dist.matrix,orthogroups,empirical.data)
{
  dist.from.target <- dist.matrix[,target.species]
  closest.species <- names(dist.from.target[which.min(dist.from.target)])
  
  k1.phi.target <- k1.phi %>% 
    dplyr::select(Orthogroups,!!as.name(target.species)) %>%
    dplyr::rename(Phi_K1 = !!as.name(target.species))
  k2.phi.target <- k2.phi %>% 
    dplyr::select(Orthogroups,!!as.name(target.species)) %>%
    dplyr::rename(Phi_K2 = !!as.name(target.species))
  
  
  ortho.species <- orthogroups %>% 
    dplyr::select(Orthogroups,!!as.name(target.species),!!as.name(closest.species))
  ortho.species <- ortho.species %>% 
    left_join(empirical.data[[closest.species]],
              by=setNames("GeneID",closest.species )
              )
  ortho.species <- ortho.species %>% 
    left_join(k1.phi.target,by="Orthogroups") %>%
    left_join(k2.phi.target,by="Orthogroups") %>%
    dplyr::select(Orthogroups,Empirical,Phi_K1,Phi_K2) %>%
    filter(!is.na(Empirical) & !is.na(Phi_K1)) 
  return(ortho.species)
}

comparePhiEmpAcrossSpecies <- function(target.species,k1.phi,k2.phi,dist.matrix,orthogroups,empirical.data)
{
  dist.from.target <- dist.matrix[,target.species]
  closest.species <- names(dist.from.target[which.min(dist.from.target)])
  
  ortho.species <- createEmpvsROCdf(target.species,k1.phi,k2.phi,dist.matrix,orthogroups,empirical.data)
  
  ortho.species.long <- ortho.species %>% 
    pivot_longer(starts_with("Phi"),names_to = "Model",values_to="Phi")
  
  across.species.corr <- ortho.species.long %>% 
    group_by(Model) %>% 
    summarize(cor.test(Empirical,Phi,method="spearman",use="complete.obs") %>% tidy()) %>% 
    dplyr::select(Model,estimate,p.value) %>%
    pivot_wider(values_from = c(estimate,p.value),names_from = Model) %>%
    mutate(Compared.to = closest.species,
           Divergence = unname(dist.from.target[which.min(dist.from.target)]) )
  return(across.species.corr)
}


plotSpecies <- function(species.df,cub=c("Phi_Shared_Mutation","Phi_Variable_Mutation"))
{
  title <- cleanSpeciesLabels(unique(species.df$Species))
  species.df <- species.df %>% filter(CUB %in% cub)
  species.df.wide <- species.df %>% pivot_wider(id_cols = c("Species","GeneID","Empirical"),names_from="CUB",values_from = "Predicted")
  species.df$CUB <- factor(species.df$CUB,levels=c(cub[1],cub[2]))
  levels(species.df$CUB) <- c("ConstMut","VarMut")
  emp.vs.pred <- ggplot(species.df,aes(x=Empirical,y=Predicted)) + geom_point(size=0.5,show.legend = F) + 
               scale_x_log10(labels = trans_format("log10", math_format(10^.x))) + 
               scale_y_log10(labels = trans_format("log10", math_format(10^.x))) +
               theme_cowplot() +
               #viridis::scale_color_viridis(option = "magma") + 
               #scale_color_manual(values = c("#E41A1C","#377EB8"),labels = c("Lower GC3% ","Higher GC3%"),name = "Gene Cluster") + 
               stat_cor(method="spearman",label.sep = "\n",label.x.npc = "left",label.y.npc = "top",show.legend = F) +
               stat_cor(mapping=aes(x=Empirical,y=Predicted),method="spearman",label.sep = "\n",label.x.npc = "left",label.y.npc = "bottom",inherit.aes=F) +
               facet_wrap(~CUB) +
               ggtitle(title) +
               theme(aspect.ratio=1)
  k1.vs.k2 <- ggplot(species.df.wide,aes(x=!!as.name(cub[1]),y=!!as.name(cub[2]))) + 
              geom_point(size=0.5) +
              scale_x_log10(labels = trans_format("log10", math_format(10^.x))) + 
              scale_y_log10(labels = trans_format("log10", math_format(10^.x))) +
              theme_cowplot() +
              #scale_color_manual(values = c("#E41A1C","#377EB8"),labels = c("Lower GC3% ","Higher GC3%"),name = "Gene Cluster") + 
              xlab("Predicted (ConstMut)") +
              ylab("Predicted (VarMut)") +
              stat_cor(aes(x=!!as.name(cub[1]),y=!!as.name(cub[2])),method="spearman",label.sep = "\n",label.x.npc = "left",label.y.npc = "top",show.legend = F,inherit.aes = F) +
              theme(legend.position="top",legend.text = element_text(size=10),legend.title = element_text(size=12)) +
               theme(aspect.ratio=1)
  
  plot_grid(emp.vs.pred,k1.vs.k2,ncol=2,align = "h", axis = "bt",rel_widths = c(1,0.5))
}

boot.cor.diff.test <- function(method,data,indices)
{
  d <- data[indices,] # allows boot to select sample
  corr.k1 <- cor(d$Empirical,d$Phi_K1,method=method)
  corr.k2 <- cor(d$Empirical,d$Phi_K2,method=method)
  diff <- corr.k2 - corr.k1 ## how much does allowing the extra mutation bias parameters change the 
  return(diff)
}


```

```{r warning = F}

fungi.tree <- read.tree("../Data/tree_with_cds_labels.nwk")
all.species <- readLines("../Data/all_fungi.txt")
fungi.tree <- cleanTree(fungi.tree,all.species)
dist.matrix <- cophenetic.phylo(fungi.tree)

species.w.emp <- list.files("../Data/Expression/",full.names = F,pattern=".max.cds")
empirical.data.file <- list.files("../Data/Expression/",full.names = T,include.dirs = F,pattern=".max.cds")
names(empirical.data.file) <- species.w.emp


dist.matrix <- dist.matrix[species.w.emp,]

empirical.data <- purrr::map(empirical.data.file,function(x) {
  read_csv(x,col_types = cols()) %>% 
    mutate(across(contains("tpm_kallisto"),~na_if(., 0))) %>%
    mutate(across(contains("tpm_kallisto"),log)) %>%
    mutate(
      Log.Mean.Expression=rowMeans(dplyr::select(.,contains("tpm_kallisto")),na.rm=T),
      Empirical=exp(Log.Mean.Expression),
      GeneID=str_remove(GeneID,"-mRNA-1")) %>% 
      dplyr::select(-contains("tpm_kallisto"),-Log.Mean.Expression)
    })

k1.phi <- read_csv("../Post_analysis/phi_k1_shen_etal_ortholog_matrix_2022_07_08.tsv",col_types = cols())  %>% 
       column_to_rownames("Orthogroup") %>%
       rename_with(~cleanColumnNames(.x,fungi.tree$tip.label)) %>%
       rownames_to_column("Orthogroups")

k2.phi <- read_csv("../Post_analysis/phi_k2_selectionShared_shen_etal_ortholog_matrix_2022_07_08.tsv",col_types = cols())  %>% 
       column_to_rownames("Orthogroup") %>%
       rename_with(~cleanColumnNames(.x,fungi.tree$tip.label)) %>%
       rownames_to_column("Orthogroups")


orthogroups <- read_tsv("../Data/shen_etal_ortholog_matrix_2021_12_17.tsv",col_types = cols())
orthogroups <- orthogroups %>% 
       column_to_rownames("Orthogroup") %>%
       rename_with(~cleanColumnNames(.x,fungi.tree$tip.label)) %>%
       rownames_to_column("Orthogroups")

names(all.species) <- all.species


roc.emp.df <- lapply(all.species,createEmpvsROCdf,
                      k1.phi = k1.phi,
                      k2.phi = k2.phi,
                      dist.matrix = dist.matrix,
                      orthogroups = orthogroups,
                      empirical.data = empirical.data) %>% 
  bind_rows(.id="Species")


compare.emp <- lapply(all.species,comparePhiEmpAcrossSpecies,
                      k1.phi = k1.phi,
                      k2.phi = k2.phi,
                      dist.matrix = dist.matrix,
                      orthogroups = orthogroups,
                      empirical.data = empirical.data) %>% 
  bind_rows(.id="Species")

clades <- read_tsv("../Data/clades.txt")
clades <- clades %>% 
  dplyr::slice(match(fungi.tree$tip.label,file_name_id)) %>%
  dplyr::rename(Species=file_name_id,Clade=Major.clade)


compare.emp <- compare.emp %>% 
  left_join(clades,by="Species")


```



```{r}

compare.emp <- compare.emp %>%
  mutate(Diff = estimate_Phi_K2 - estimate_Phi_K1,
    Improvement = Diff/abs(estimate_Phi_K1)) 
compare.emp.improved <- compare.emp %>%
  filter(Improvement >= 0.25 & Diff > 0 & estimate_Phi_K2 > 0)
improved.fits.species <- compare.emp.improved %>%
  dplyr::select(Species) %>%
  deframe()

write(improved.fits.species,"../Data/improved_species_by_gene_expression_25_percent_2023_05_03.txt",ncolumns = 1)

compare.emp.unimproved <- compare.emp %>%
  filter(Improvement < 0.25 | (Improvement >= 0.25 & estimate_Phi_K2 < 0))



compare.emp <- compare.emp %>% 
  mutate(estimate_Phi = ifelse(Species %in% improved.fits.species,estimate_Phi_K2,estimate_Phi_K1))


p <- ggplot(compare.emp,aes(estimate_Phi_K1,estimate_Phi_K2)) +
  geom_point() + 
  xlab("Phi vs. Empirical (ConstMut)") +
  ylab("Phi vs. Empirical (VarMut)") +
  theme_cowplot() + 
  stat_cor(method="spearman") +
  geom_abline(intercept=0,slope=1,linetype="dashed") +
  facet_wrap(~Clade)
p


compare.emp <- compare.emp %>% 
  left_join(compare.emp %>% dplyr::select(Species,estimate_Phi),by=c("Compared.to"="Species"),suffix=c("","_Reference"))
compare.emp <- compare.emp %>%
  mutate(Corr.Diff = estimate_Phi - estimate_Phi_Reference)
compare.emp.non.ref <- compare.emp %>% 
  filter(Corr.Diff != 0)

compare.emp.grouped <- compare.emp.non.ref %>% 
  group_by(Compared.to,Divergence) %>%
  summarize(Mean.Corr.Diff=mean(Corr.Diff),
            Total=n())

corr.diff.plot <- ggplot(compare.emp.non.ref,aes(x=Divergence,y=Corr.Diff)) +
  geom_point(aes(color=Compared.to),show.legend =F) +
  stat_cor(aes(x=Divergence,y=Corr.Diff),method="spearman",label.sep="\n",inherit.aes = F,label.x.npc = "center",label.y = -0.5) +
  theme_cowplot() +
  ylab("Difference in Spearman Correlation") +
  xlab("Divergence time (MYA)") +
  #ggtitle("Correlation between ROC and RNA-Seq\nRelative to Reference Species") +
  theme(aspect.ratio=1)
corr.diff.plot

ggsave2("../Figures/All_species/S01_phi_relative_to_refence_species.pdf",plot=corr.diff.plot,height=5,width=5)

```



```{r echo = F, warning = F,fig.width=16,fig.height=7}
roc.emp.df.long <- roc.emp.df %>%
  pivot_longer(contains("Phi"),names_to="CUB",values_to="Predicted") %>%
  dplyr::rename(GeneID=Orthogroups) %>%
  group_by(Species) %>%
  group_split()


purrr::map(roc.emp.df.long,plotSpecies,cub=c("Phi_K1","Phi_K2"))

```



```{r}

species <- improved.fits.species
deta.k1.files <- file.path("../Final_runs/Results_k_1/",species,"run_2","Parameter_est",paste0(species,"_Selection.csv"))
dm.k1.files <- file.path("../Final_runs/Results_k_1/",species,"run_2","Parameter_est",paste0(species,"_Mutation.csv"))
deta.k2.files <- file.path("../Final_runs/Results_k_2_selectionShared/",species,"run_2","Parameter_est","1_Selection.csv")
dm.k2.1.files <- file.path("../Final_runs/Results_k_2_selectionShared/",species,"run_2","Parameter_est","1_Mutation.csv")
dm.k2.2.files <- file.path("../Final_runs/Results_k_2_selectionShared/",species,"run_2","Parameter_est","2_Mutation.csv")

names(deta.k1.files) <- species
names(dm.k1.files) <- species
names(deta.k2.files) <- species
names(dm.k2.1.files) <- species
names(dm.k2.2.files) <- species

deta.k1 <- purrr::map(deta.k1.files,read_csv,col_types=cols()) %>% bind_rows(.id="Species") %>% 
  dplyr::select(Species,AA,Codon,Mean) %>% 
  filter(Mean != 0) %>%
  dplyr::rename(Selection.K1 = Mean)
dm.k1 <- purrr::map(dm.k1.files,read_csv,col_types=cols()) %>% bind_rows(.id="Species") %>% 
  dplyr::select(Species,AA,Codon,Mean) %>% 
  filter(Mean != 0) %>%
  dplyr::rename(Mutation.K1 = Mean)
deta.k2 <- purrr::map(deta.k2.files,read_csv,col_types=cols()) %>% bind_rows(.id="Species") %>% 
  dplyr::select(Species,AA,Codon,Mean) %>% 
  filter(Mean != 0) %>%
  dplyr::rename(Selection.K2 = Mean)
dm.k2.1 <- purrr::map(dm.k2.1.files,read_csv,col_types=cols()) %>% bind_rows(.id="Species") %>% 
  dplyr::select(Species,AA,Codon,Mean) %>% 
  filter(Mean != 0) %>%
  dplyr::rename(Mutation.K2.1 = Mean)
dm.k2.2 <- purrr::map(dm.k2.2.files,read_csv,col_types=cols()) %>% bind_rows(.id="Species") %>% 
  dplyr::select(Species,AA,Codon,Mean) %>% 
  filter(Mean != 0) %>%
  dplyr::rename(Mutation.K2.2 = Mean)

csp.df <- list(deta.k1,dm.k1,deta.k2,dm.k2.1,dm.k2.2) %>% purrr::reduce(left_join, by = c("Species","AA","Codon"))

csp.df <- csp.df %>% mutate(Mutation.K2.Diff = Mutation.K2.1 - Mutation.K2.2)
```


```{r fig.width=9,fig.height=9}
csp.df.split <- csp.df %>% group_by(Species) %>% group_split()

plotCSP <- function(df)
{
  species <- unique(cleanSpeciesLabels(df$Species))
  sel <- ggplot(df,aes(x= Selection.K1,y=Selection.K2)) + geom_point() +
        theme_cowplot() +
        ggtitle(species) +
        theme(aspect.ratio = 1) +
        stat_cor(method="spearman",label.sep = "\n") + 
        xlab("Selection (K = 1)") +
        ylab("Selection (K = 2)") 
  mut.1 <- ggplot(df,aes(x= Mutation.K1,y=Mutation.K2.1)) + geom_point() +
        theme_cowplot() +
        theme(aspect.ratio = 1) +
        stat_cor(method="spearman",label.sep = "\n") + 
        xlab("Mutation (K = 1)") +
        ylab("Mutation Cluster 1 (K = 2)") 
  mut.2 <- ggplot(df,aes(x= Mutation.K1,y=Mutation.K2.2)) + geom_point() +
        theme_cowplot() +
        theme(aspect.ratio = 1) +
        stat_cor(method="spearman",label.sep = "\n") + 
        xlab("Mutation (K = 1)") +
        ylab("Mutation Cluster 2 (K = 2)") 
  
  mut.k2 <- ggplot(df,aes(x= Mutation.K2.1,y=Mutation.K2.2)) + geom_point() +
        theme_cowplot() +
        theme(aspect.ratio = 1) +
        stat_cor(method="spearman",label.sep = "\n") + 
        xlab("Mutation Cluster 1 (K = 2)") +
        ylab("Mutation Cluster 2 (K = 2)")
  
  overall <- plot_grid(sel,mut.1,mut.2,mut.k2,nrow=2,ncol=2)
  return(overall)
  
}

purrr::map(csp.df.split,plotCSP)



```


```{r fig.width=9}
tree.plot <- ggtree(fungi.tree)

const.tree.plot <- treeTraitPlot(tree.plot,compare.emp,"estimate_Phi_K1","Spearman correlation\nConstMut")
var.tree.plot <- treeTraitPlot(const.tree.plot,compare.emp,"estimate_Phi_K2","Spearman correlation\nVarMut")
var.tree.plot <- treeTraitPlot(var.tree.plot,compare.emp,"Diff","Difference\nVarMut - ConstMut")
var.tree.plot <- var.tree.plot + theme_tree2()
var.tree.plot
cor.tree.plot <- treeTraitPlot(tree.plot,compare.emp,"estimate_Phi","Spearman correlation\nObs. vs. Pred. Gene Expr.")
cor.tree.plot <- cor.tree.plot + theme_tree2()
cor.tree.plot
ggsave2("../Figures/All_species/S02_constmut_vs_varmut.pdf",plot = var.tree.plot,width=9)
ggsave2("../Figures/All_species/01_final_phi.pdf",plot = cor.tree.plot,width=9)


```



```{r}
write_csv(compare.emp,"../2023-05-04_compare_phi_vs_empirical_k1_vs_k2_roc_fits_all_species.csv")
print(nrow(compare.emp %>% filter(estimate_Phi > 0))/327)
print(paste("Number of species for which VarMut model improved model fit by 25%:",length(improved.fits.species)/327))

compare.emp %>% filter(Species %in% improved.fits.species) %>% summarize(median(Diff))
compare.emp %>% filter(!Species %in% improved.fits.species) %>% summarize(median(Diff))
```